package com.cbcds.aventura.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF456813)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFC4F18B)
val light_onPrimaryContainer = Color(0xFF102000)
val light_secondary = Color(0xFF586249)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFDCE7C7)
val light_onSecondaryContainer = Color(0xFF161E0B)
val light_tertiary = Color(0xFF386663)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFBCECE7)
val light_onTertiaryContainer = Color(0xFF00201E)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFDFCF5)
val light_onBackground = Color(0xFF1B1C18)
val light_surface = Color(0xFFFDFCF5)
val light_onSurface = Color(0xFF1B1C18)
val light_surfaceVariant = Color(0xFFE1E4D5)
val light_onSurfaceVariant = Color(0xFF44483D)
val light_outline = Color(0xFF75796C)
val light_inverseOnSurface = Color(0xFFF2F1E9)
val light_inverseSurface = Color(0xFF30312C)
val light_inversePrimary = Color(0xFFA9D472)
val light_surfaceTint = Color(0xFF456813)

val dark_primary = Color(0xFFA9D472)
val dark_onPrimary = Color(0xFF1F3700)
val dark_primaryContainer = Color(0xFF304F00)
val dark_onPrimaryContainer = Color(0xFFC4F18B)
val dark_secondary = Color(0xFFC0CBAC)
val dark_onSecondary = Color(0xFF2A331E)
val dark_secondaryContainer = Color(0xFF404A33)
val dark_onSecondaryContainer = Color(0xFFDCE7C7)
val dark_tertiary = Color(0xFFA0D0CB)
val dark_onTertiary = Color(0xFF003734)
val dark_tertiaryContainer = Color(0xFF1F4E4B)
val dark_onTertiaryContainer = Color(0xFFBCECE7)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1B1C18)
val dark_onBackground = Color(0xFFE3E3DB)
val dark_surface = Color(0xFF1B1C18)
val dark_onSurface = Color(0xFFE3E3DB)
val dark_surfaceVariant = Color(0xFF44483D)
val dark_onSurfaceVariant = Color(0xFFC5C8BA)
val dark_outline = Color(0xFF8F9285)
val dark_inverseOnSurface = Color(0xFF1B1C18)
val dark_inverseSurface = Color(0xFFE3E3DB)
val dark_inversePrimary = Color(0xFF456813)
val dark_surfaceTint = Color(0xFFA9D472)

val seed = Color(0xFFDBEBC1)

